// <auto-generated />
using DataWarehousePower.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataWarehousePower.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608024300_AddUserColumnPreferences")]
    partial class AddUserColumnPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataWarehousePower.Models.ReportStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ReportStaff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Age = 45,
                            Name = "Bob Smith"
                        },
                        new
                        {
                            Id = 3,
                            Age = 28,
                            Name = "Carol Williams"
                        },
                        new
                        {
                            Id = 4,
                            Age = 52,
                            Name = "David Brown"
                        },
                        new
                        {
                            Id = 5,
                            Age = 35,
                            Name = "Eve Davis"
                        });
                });

            modelBuilder.Entity("DataWarehousePower.Models.UserColumnPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ColumnJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserColumnPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
