// <auto-generated />
using DataWarehousePower.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataWarehousePower.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608100019_AddReportEngine")]
    partial class AddReportEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataWarehousePower.Models.ReportColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReportDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportDefinitionId");

                    b.ToTable("ReportColumns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultLabel = "ID",
                            DisplayOrder = 1,
                            PropertyName = "Id",
                            ReportDefinitionId = 1
                        },
                        new
                        {
                            Id = 2,
                            DefaultLabel = "Name",
                            DisplayOrder = 2,
                            PropertyName = "Name",
                            ReportDefinitionId = 1
                        },
                        new
                        {
                            Id = 3,
                            DefaultLabel = "Age",
                            DisplayOrder = 3,
                            PropertyName = "Age",
                            ReportDefinitionId = 1
                        });
                });

            modelBuilder.Entity("DataWarehousePower.Models.ReportDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ReportDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ReportName = "Staff Report",
                            SourceTable = "ReportStaff"
                        });
                });

            modelBuilder.Entity("DataWarehousePower.Models.ReportStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ReportStaff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Age = 45,
                            Name = "Bob Smith"
                        },
                        new
                        {
                            Id = 3,
                            Age = 28,
                            Name = "Carol Williams"
                        },
                        new
                        {
                            Id = 4,
                            Age = 52,
                            Name = "David Brown"
                        },
                        new
                        {
                            Id = 5,
                            Age = 35,
                            Name = "Eve Davis"
                        });
                });

            modelBuilder.Entity("DataWarehousePower.Models.UserColumnPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(0);

                    b.Property<int>("ReportDefinitionId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("ColumnJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "ReportDefinitionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserColumnPreferences");
                });

            modelBuilder.Entity("DataWarehousePower.Models.ReportColumn", b =>
                {
                    b.HasOne("DataWarehousePower.Models.ReportDefinition", "Report")
                        .WithMany("Columns")
                        .HasForeignKey("ReportDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DataWarehousePower.Models.ReportDefinition", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
